Path-Check/safeplaces-backend

safe-places-server/.dockerignore, safe-places-server/.env.template, safe-places-server/Dockerfile, safe-places-server/README.md, safe-places-server/knexfile.js, safe-places-server/routes/index.js, safe-places-server/test/api_tests.js
- Pulls out DB connection url from development and testing env as ENV variable
- Implements /health API
=> Dockerfile added

expressjs/app.js, expressjs/routes/index.js, expressjs/test/api_tests.js
Corrects to new login JWT scheme
=> CORS handling added to API middleware

expressjs/.env.template, expressjs/db/seeds/development/users_seed.js, expressjs/db/seeds/test/users_seed.js, expressjs/package-lock.json, expressjs/package.json, expressjs/test/api_tests.js
Fixes missing package for CORS
Note: Remember to rebuild your docker volume: `docker volume rm expressjs_node_modules`
=> SEED_MAPS_API_KEY added to seed the maps api key to DB

expressjs/db/knex.js, expressjs/db/migrations/20200420011122_organizations.js, expressjs/db/migrations/20200420011123_users.js, expressjs/db/migrations/20200428173125_extension_postgis.js, expressjs/db/migrations/20200428174152_trails.js, expressjs/db/models/organizations.js, expressjs/db/models/trails.js, expressjs/db/seeds/development/organizations_seed.js, expressjs/db/seeds/development/users_seed.js, expressjs/db/seeds/test/organizations_seed.js, expressjs/db/seeds/test/users_seed.js, expressjs/package-lock.json, expressjs/package.json, expressjs/routes/index.js, expressjs/test/api_tests.js, expressjs/views/error.jade, expressjs/views/index.jade, expressjs/views/layout.jade
- Creates concrete API implementations for redacted trails GET and POST
- Organization implementation
=> Concrete API implementations for redacted_trails

expressjs/.env.template, expressjs/db/seeds/development/users_seed.js, expressjs/db/seeds/test/users_seed.js, expressjs/test/api_tests.js
=> [Missed PR during branch reset] SEED_MAPS_API_KEY environment variable added

expressjs/db/migrations/20200428174152_trails.js, expressjs/dbsetup.sh, expressjs/routes/index.js, expressjs/test/api_tests.js
String length to be of max size 255
Little better handling of negative test cases
=> Fixes identifier of trails to be a string instead of UUID

expressjs/db/migrations/20200501174613_publications.js, expressjs/db/models/organizations.js, expressjs/db/models/publications.js, expressjs/db/models/trails.js, expressjs/dbsetup.sh, expressjs/routes/index.js, expressjs/test/api_tests.js
Concrete implementations for /safe_paths APIs POST & GET
Resolves #32
=> Concrete implementations for /safe_paths APIs POST & GET

expressjs/app.js, expressjs/package-lock.json, expressjs/package.json, expressjs/routes/index.js, expressjs/test/api_tests.js
Further unit testing for /login API added
=> Test coverage module configured

expressjs/routes/index.js, expressjs/test/api_tests.js
Unit tests for /redacted_trails GET POST methods
=> Implements further unit-tests for redacted trails APIs

expressjs/README.md, expressjs/knexfile.js
=> Updates README with improved and tested postgres configuration

expressjs/public/stylesheets/style.css, expressjs/routes/index.js, expressjs/test/api_tests.js
=> Unit tests for safe_paths GET POST APIs

expressjs/.env.template, expressjs/package-lock.json, expressjs/package.json, expressjs/routes/index.js, expressjs/test/api_tests.js
=> JWT expiration logic and test for auth added

api-spec.json
I have commented the different endpoints as:
- "mandatory" i.e. as used by the former dev-mvp branch
- "extensions" as used in the nestjs server and I think the express server too
This needs much work, but have learned enough to share,  get feedback on it now.
=> Backend API spec in OpenAPI v3 format

db/seeds/development/users_seed.js, db/seeds/test/users_seed.js
fix seeds to reflect users in ldapjs/passwd and fix failing specs
=> Update DB Seeds

app/api/organization/controller.js, test/integration/organizations.test.js
Include org id and completedOnboarding flag to GET /organization response payload.
=> PLACES-300 Cannot GET organization configuration

app/api/case/controller.js, app/api/case/router.js, db/models/cases.js, db/models/points.js, test/integration/case.test.js
The contact tracer needs a way of getting all points of concern for a collection of cases.
=> PLACES-284 Add GET /cases/points endpoint

app/api/case/controller.js, db/migrations/20200603105100_add_consented_to_publishing_at_cases.js, db/models/cases.js, test/integration/case.test.js
Jira Ticket: https://pathcheck.atlassian.net/browse/PLACES-257
- Add a new field on the `cases` database table to track when a user consented to having their data published
- Update the existing `consentToPublish` controller action in the cases controller to set the value on the new field in the database when called
=> PLACES-257 Add consented_to_publishing_at field on cases table

db/seeds/development/organizations_seed.js, db/seeds/development/users_seed.js, db/seeds/test/organizations_seed.js, db/seeds/test/users_seed.js, ldapjs/passwd
Jira Ticket: https://pathcheck.atlassian.net/browse/PLACES-328
This issue was arose because the new user was created in the staging ldap instance but not in the database. I've updated the seeds to add the new test user mentioned in the corresponding jira ticket.
=> PLACES-328  User can obtain token, but other calls return user not found

.env.template
Updated the seed `JWT_SECRET` env var to be a 64 character randomly generated string.
=> PLACES-321 Insufficient entropy in the JWT token

app/api/case/controller.js, db/models/cases.js, src/server/express.js
I also yanked out a bunch of duplicate bodyparsers.
=> [PLACES-333] Increase the Allowed size in Express

app/api/organization/controller.js, app/lib/publicationFiles.js, db/migrations/20200612151326_chag_timeframe.js, db/models/organizations.js, db/seeds/development/organizations_seed.js, db/seeds/test/organizations_seed.js, src/server/errorHandler.js, test/integration/case.test.js, test/integration/organizations.test.js
Aligning with Spec.
Also fixes logging issue.
=> [PLACES-372] Fix on Threshold Count to Timeline variable

db/common/service.js, db/models/accessCodes.js
Delete access codes older than 2 hours when a new code is generated
=> PLACES-376 Expire access codes

db/models/upload.js, test/lib/mockData.js
This should merge before https://github.com/Path-Check/safeplaces-backend-ingest/pull/10
=> PLACES-378 Removed hash from uploaded point model

base/deployment.yml
=> cleaning env deployment

.github/workflows/google-express-tests.yaml, src/server/passport.js, test/integration/login.test.js, tests/tests/FASTAPI.postman_environment.json
Changes DN resolution to relative instead of absolute.
Also increased robustness of invalid credentials callback by resolving as long as the search query ends.
=> [Hotfix LDAP] Fix LDAP search and resolution

.github/workflows/google-express-tests.yaml, base/deployment.yml, src/server/passport.js, test/integration/login.test.js, tests/tests/FASTAPI.postman_environment.json
- Update deployment envs
- Resolve LDAP issues
=> Dev => Staging

app/api/auth/controller.js, src/server/passport.js
* Fix JWT expiration
* Fix JWT expiration
=> [Hotfix JWT] Fix JWT expiration (#162)

.github/CODEOWNERS
Create notification list to automatically request individuals for PR review.
=> Auto-request individuals for PR review

app/api/case/controller.js
Allowing the FE to pass a null value in order to set nickname to `null` on points.
=> PLACES-458 Allow users to remove nickname from a set of points

package-lock.json, package.json
This issue was caused by a bug fixed in v0.1.5 of the safeplaces-data-layer lib.
=> PLACES-475 For manually generated data extending over a time period, data points at 300k secs apart instead of 300 secs.

tests/tests/backend_collection.json
1. test that CT login works
2. test that CT cannot update org config
3. test that CT can get org config
=> Add 3 Newman tests for contact tracer user

env.schema.json
Include the Auth0 environment variables in the environment variable validator
=> Update env schema

app/lib/writeToGCSBucket.js
=> Jh debug staging
